/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '3/21/23, 12:40 PM' 
 * Generated by 'u63318200' 
 * Generated on server 'ODAWS01-APSE1-2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.12.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' 
 * Generated on web client 'https://odamid-apse1-2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT%252B07%253A00&ticket=ST-117115-VccZryqbyn0FEDJdNNwq-cas' 
 *
 */

proc sort data=SASHELP.FAILURE out=WORK.SORTTempTableSorted;
	by Process Day;
run;

proc transpose data=WORK.SORTTempTableSorted 
		out=work.ChrisDarren54804_Transposed;
	var Count;
	id Cause;
	by Process Day;
run;

proc print data=work.ChrisDarren54804_Transposed(obs=10);
	title "Subset of work.ChrisDarren54804_Transposed";
run;

title;

proc delete data=WORK.SORTTempTableSorted;
run;